### ISSUE TITLE
Icons are wrong

### ISSUE THREAD

**Issue by cjwelborn** [deviant-io/github-user-badge#2]
Decided to check on my badge to see if you had made any changes and make sure everything was still running smoothly, but the font/icons are messed up:
![image](https://cloud.githubusercontent.com/assets/3335984/8389717/20313a26-1c3c-11e5-8436-58882f923d87.png)

I get the same thing for the [deviant.io](https://deviant.io) preview.

**Comment by calvinfroedge** [comment]
Is it possible that you're using a new computer or perhaps a new OS install? font-awesome (font-awesome.com) uses some font packs that have some known issues on linux.

**Comment by cjwelborn** [comment]
Same machine, but I've had a few updates recently. I'll do some checking and see if there may have been some regressions or incompatible changes.

**Comment by cjwelborn** [comment]
Couldn't find any changes to my system I thought would cause this. FontAwesome renders all icons properly for me (on their site and locally). The missing icons are specifically from [Octicons](https://octicons.github.com/) I think. One of the icons that is messing up is the "book" icon, for the repo count. Using the octicon font and this css (that matches your badge css):
```css
.octicon-repo:before {
  content: '\f001' 
}
```

It renders properly on https://octicons.github.com/, but I downloaded octicons and I set up a local test anyway. Coming from the source, and locally, everything seems to work. For deviant.io I get the ﬁ ligature.

**Comment by calvinfroedge** [comment]
In this case, may be a side effect of it being inside a web component.
Thanks for the help checking this.

On Fri, Jun 26, 2015 at 11:53 PM, Christopher Welborn <
notifications@github.com> wrote:

> Couldn't find any changes to my system I thought would cause this.
> FontAwesome renders all icons properly for me (on their site and locally).
> The missing icons are specifically from Octicons
> <https://octicons.github.com/> I think. One of the icons that is messing
> up is the "book" icon, for the repo count. Using the octicon font and this
> css (that matches your badge css):
>
> .octicon-repo:before {
>   content: '\f001'
> }
>
> It renders properly on https://octicons.github.com/, but I downloaded
> octicons and I set up a local test anyway. Coming from the source, and
> locally, everything seems to work. For deviant.io I get the ﬁ ligature.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/deviant-io/github-user-badge/issues/2#issuecomment-115953374>
> .
>



-- 
Respectfully yours,
*Calvin Froedge*
Github <https://github.com/calvinfroedge> | LinkedIn
<http://www.linkedin.com/in/calvinfr>  |  (415) 494-9853

Want a badge for displaying your Github contribution history on your
personal site? Check out Deviant <https://deviant.io>.

**Comment by cjwelborn** [comment]
Ok, so running the basic code needed for this badge (locally) produces the same problem. However, if I include a copy of `font-awesome.css` and `octicons.css` it works fine. Like this:
```html
        <!-- Local also works: href='./../fontawesome/font-awesome/css/font-awesome.css' -->
        <link type='text/css' rel='stylesheet' href='http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css'/>
        <!-- Local also works: href='./../octicons/octicons/octicons.css' -->
        <link type='text/css' rel='stylesheet' href='http://cdnjs.cloudflare.com/ajax/libs/octicons/2.4.1/octicons.min.css'/>
```

It only fails on deviant.io (or by loading the badge on my site). I don't know what would cause this.

**Comment by calvinfroedge** [comment]
I'm pretty sure it's an issue with web component styles. If including
fontawesome and octicons fixes the issue for you, that's good, you should
do that as a temporary fix. I'll dig into why this is happening for you
(could you send me browser info?).

On Sat, Jun 27, 2015 at 1:59 PM, Christopher Welborn <
notifications@github.com> wrote:

> Ok, so running the basic code needed for this badge (locally) produces the
> same problem. However, if I include a copy of font-awesome.css and
> octicons.css it works fine. Like this:
>
>         
>         <link type='text/css' rel='stylesheet' href='http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css'/>
>         
>         <link type='text/css' rel='stylesheet' href='http://cdnjs.cloudflare.com/ajax/libs/octicons/2.4.1/octicons.min.css'/>
>
> It only fails on deviant.io (or by loading the badge on my site). I don't
> know what would cause this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/deviant-io/github-user-badge/issues/2#issuecomment-116109206>
> .
>



-- 
Respectfully yours,
*Calvin Froedge*
Github <https://github.com/calvinfroedge> | LinkedIn
<http://www.linkedin.com/in/calvinfr>  |  (415) 494-9853

Want a badge for displaying your Github contribution history on your
personal site? Check out Deviant <https://deviant.io>.

**Comment by calvinfroedge** [comment]
Also, I'll probably just swap the fonts out for images, as they behave more
reliably.

On Sat, Jun 27, 2015 at 1:59 PM, Christopher Welborn <
notifications@github.com> wrote:

> Ok, so running the basic code needed for this badge (locally) produces the
> same problem. However, if I include a copy of font-awesome.css and
> octicons.css it works fine. Like this:
>
>         
>         <link type='text/css' rel='stylesheet' href='http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css'/>
>         
>         <link type='text/css' rel='stylesheet' href='http://cdnjs.cloudflare.com/ajax/libs/octicons/2.4.1/octicons.min.css'/>
>
> It only fails on deviant.io (or by loading the badge on my site). I don't
> know what would cause this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/deviant-io/github-user-badge/issues/2#issuecomment-116109206>
> .
>



-- 
Respectfully yours,
*Calvin Froedge*
Github <https://github.com/calvinfroedge> | LinkedIn
<http://www.linkedin.com/in/calvinfr>  |  (415) 494-9853

Want a badge for displaying your Github contribution history on your
personal site? Check out Deviant <https://deviant.io>.

**Comment by cjwelborn** [comment]
Ok that sounds good, and I'll just include the needed css on my site. I use `Chrome 43.0.2357.130` on `Kubuntu 14.04` if that's what you mean.
